### ISSUE TITLE
Admin signup Page Design Requirements Analysis

### ISSUE THREAD

**Issue by Srivishnu2119** [Srivishnu2119/EmergencyResponseSystem#12]
As a developer, In order to construct a user-friendly, safe, and efficient interface for enrolling new administrative users, it is essential to collect requirements for an admin signup page.

**Comment by Poojarao498** [comment]
As part of the user story in sprint 1, 
I have completed Analysing the requirements for the signup page of the admin.
Determined the specific information required for the admin registration such as phone number, emailid/username,password and confirm password and hospital name.
The password and confirm password should be same. If they are not same it should show error like "Password and Confirm Password are not same,Fileds cannot be empty".
Hospital name, Phone number,Username, passsword and confirm password should be in red color font and beside them there should be a textbox to enter the details.
At last there should be submit button with the blue color.
