### ISSUE TITLE
Patient Module Dashboard Requirements Analysis

### ISSUE THREAD

**Issue by Srivishnu2119** [Srivishnu2119/EmergencyResponseSystem#13]
As a developer, It's crucial to collect requirements for a patient module dashboard before building a functional and approachable user interface for healthcare applications. It will be easier to develop a patient module dashboard that meets the demands of both patients and healthcare professionals, improves patient involvement, and improves the standard of care in healthcare apps by gathering these requirements.

**Comment by AsishInuganti** [comment]
In the patient module there will be a Doctor name, Doctor specialization, Hospital name, symptoms, Appointment date, Status of the doctor to be assigned.
1. To Book the appointment with the doctor you have to enter the symptoms of the disease.
2. Then you can see the name of the doctor with the specialization and the hospital that can treat you.
3. Now you can book the appointment with the available dates.
4. you can see the Status of the doctor to be assigned
5. After booking an appointment you can logout of your account
