### ISSUE TITLE
Analysing the requirements what needs to be on the front end welcome page.

### ISSUE THREAD

**Issue by Srivishnu2119** [Srivishnu2119/EmergencyResponseSystem#14]
As a Developer, It should include clear calls to action, such as "Sign Up" or "Log In," to facilitate the entry into the platform.

- Facilitate the login page to differentiate for users(Admin/Patient/Doctor).
- Should have the checks for user login with user id and password.
- User friendly login page to use for the customers.
-

**Comment by upendar116** [comment]
as part of the user story in sprint 1
i had completed analyzing the requirements for the front end welcome page.
determined the specific information required for the welcome page such as admin login, doctor login, patient login.
-> when we select admin login page it redirect to login page it shows to enter user id and password to enter if you have a account or else it shows sing up to create the account and then login it shows the dashboard of the uses and he cam access the permission and the users . 
->when we select doctor  login page it redirect to login page it shows to enter user id and password to enter if you have a account or else it shows sing up to create the account and then login it shows the profile and dashboard of the doctor where he can manage the schedule and upcoming  appointments for the patients.
->when we select patient login page it redirect to login page it shows to enter user id and password to enter if you have a account or else it shows sing up to create the account and then we login it shows the profile about the patient and reports and he can access to the make a appointment for doctor.
