### ISSUE TITLE
Definining requirements for the Emergency Response System project

### ISSUE THREAD

**Issue by Srivishnu2119** [Srivishnu2119/EmergencyResponseSystem#2]
As a team member, to define the high-level requirements for the Emergency Response System to understand the project scope

**Comment by tejaswinikanukunta** [comment]
Software requirements for the project:
Front end software: HTML and CSS
Backend software: PHP
Operating system: Windows 10

Hardware requirements: PC with minimum 10 GB harddisk and 512 MB RAM
