### ISSUE TITLE
Admin Login Page Design Requirements Analysis

### ISSUE THREAD

**Issue by Srivishnu2119** [Srivishnu2119/EmergencyResponseSystem#3]
As a developer,  for the purpose of designing an efficient and safe login page for administrative users, it is necessary to gather the necessary data and rules. 

- Filter the roles and permissions that Admin should have.
- Gets the highest access and can restrict other users.
- Permission to add/remove users.
- Have access to modify user appointments.
- Having access to Add/verify doctor details to approve.

**Comment by SrinivasAbburi0009** [comment]
As a developer, the admin login page is the first page that users see in the modified application. It provides Three fields:
1. Username Details
2. Password Details
3. New Users Signup Details

Details provided in the page:
-> Admin, Doctor and Patient
-> About us, Contact us
-> Social media links
